import dynamic from "next/dynamic";
import Head from "next/head";

const Body = dynamic(() => import("@/components/Body")
  .then((module) => module.Body), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body />
    </>
  );
}
